# /BE_NEUTRAL/docker-compose.yml
services:
  mongo:
    image: mongo:7.0
    container_name: pipeline_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      default:
        aliases:
          - mongo

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: pipeline_backend_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "8001:8000" # Changed to 8001 to avoid conflicts with the legacy project
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pipeline_frontend_
    restart: always
    environment:
      - VITE_API_URL=http://192.168.233.227:8001 # The frontend now calls the API on port 8001
    depends_on:
      - backend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - default

volumes:
  mongo_data: